name: CI

on:
  push:
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Solaris (SunOS) tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: ifconfig
      - uses: mondeja/solaris-vm-action@v1
        with:
          cpus: 2
          prepare: |
            uname -a
            uname -o
          run: |
            echo hello
            sh tests.sh
