name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Solaris (SunOS) tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: networksetup -listallhardwareports
      - uses: mondeja/solaris-vm-action@v1
        with:
          run: sh tests.sh
