name: Development

on:
  push:
    tags:
      - dev
  workflow_dispatch:

jobs:
  test-dev:
    name: Solaris (SunOS) tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mondeja/solaris-vm-action@dev
        with:
          run: |
            cat /etc/ssh/sshd_config
            sh tests.sh