name: Development

on:
  push:
    tags:
      - dev
  workflow_dispatch:

jobs:
  test-dev:
    name: Solaris (SunOS) tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            sol-11_4.ova
          key: sol-11_4
      - uses: mondeja/solaris-vm-action@dev
        with:
          cpus: 2
          memory: 2048
          run: |
            cat /etc/ssh/sshd_config
            sh tests.sh
